Repository TensorSpeech/TensorFlowTTS, pull requests merged in 2020-07, with the labels that each got.

#79 Update GL for batch mel and add librosa version
  notebooks/Griffin_lim_tensorflow.ipynb
  notebooks/griffin_lim_tensorflow.ipynb
  tensorflow_tts/utils/__init__.py
  tensorflow_tts/utils/griffin_lim.py
Labels: enhancement 🚀

#84 🚀 📝 Add TFLite-convertible TFFastSpeech
  tensorflow_tts/models/fastspeech.py
Labels: Feature Request 🤗, TFLite, enhancement 🚀

#87 Add FastSpeech with TFLite colab notebook file.
  notebooks/TensorFlowTTS_FastSpeech_with_TFLite.ipynb
Labels: Feature Request 🤗, TFLite, enhancement 🚀

#83 📝 🚀 Add `inference_tflite()` in `TFTacotron2`
  tensorflow_tts/models/tacotron2.py
  tensorflow_tts/utils/__init__.py
  tensorflow_tts/utils/decoder.py
Labels: Feature Request 🤗, TFLite, enhancement 🚀

#102 🚀 Refactor FastSpeech, separate encoder/decoder params.
  examples/fastspeech/conf/fastspeech.v1.yaml
  examples/fastspeech/conf/fastspeech.v3.yaml
  examples/fastspeech2/conf/fastspeech2.v1.yaml
  notebooks/TensorFlowTTS_FastSpeech_with_TFLite.ipynb
  notebooks/fastspeech_inference.ipynb
  tensorflow_tts/configs/fastspeech.py
  tensorflow_tts/configs/fastspeech2.py
  tensorflow_tts/models/fastspeech.py
  tensorflow_tts/models/fastspeech2.py
  test/test_fastspeech.py
Labels: Feature Request 🤗, enhancement 🚀

#146 Fix Android example and simplify it
  examples/android/app/src/main/AndroidManifest.xml
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/MainActivity.java
Labels: enhancement 🚀

#150 Add text processors and accept free text in Android
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/MainActivity.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/NumberNorm.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/Processor.java
  examples/android/app/src/main/res/layout/activity_main.xml
Labels: Feature Request 🤗, TFLite, enhancement 🚀

#78 Preprocess rework
  README.md
  setup.py
  tensorflow_tts/bin/compute_statistics.py
  tensorflow_tts/bin/normalize.py
  tensorflow_tts/bin/preprocess.py
  tensorflow_tts/processor/ljspeech.py
Labels: enhancement 🚀

#167 🚀 Add Auto Model, Auto Config, TFMBMelGANGenerator, Update TF 2.3.0 to CI.
  .github/workflows/ci.yaml
  README.md
  examples/fastspeech/conf/fastspeech.v1.yaml
  examples/fastspeech/conf/fastspeech.v3.yaml
  examples/fastspeech2/conf/fastspeech2.v1.yaml
  examples/fastspeech2/conf/fastspeech2.v2.yaml
  examples/fastspeech2/decode_fastspeech2.py
  examples/fastspeech2/train_fastspeech2.py
  examples/melgan.stft/conf/melgan.stft.v1.yaml
  examples/melgan.stft/train_melgan_stft.py
  examples/melgan/conf/melgan.v1.yaml
  examples/melgan/decode_melgan.py
  examples/melgan/train_melgan.py
  examples/multiband_melgan/conf/multiband_melgan.v1.yaml
  examples/multiband_melgan/decode_mb_melgan.py
  examples/multiband_melgan/train_multiband_melgan.py
  examples/tacotron2/conf/tacotron2.v1.yaml
  notebooks/fastspeech2_inference.ipynb
  notebooks/fastspeech_inference.ipynb
  notebooks/multiband_melgan_inference.ipynb
  notebooks/tacotron2_inference.ipynb
  setup.py
  tensorflow_tts/inference/__init__.py
  tensorflow_tts/inference/auto_config.py
  tensorflow_tts/inference/auto_model.py
  tensorflow_tts/models/__init__.py
  tensorflow_tts/models/fastspeech.py
  tensorflow_tts/models/fastspeech2.py
  tensorflow_tts/models/mb_melgan.py
  tensorflow_tts/models/melgan.py
  tensorflow_tts/models/tacotron2.py
  test/test_auto_model.py
Labels: enhancement 🚀
