Repository TensorSpeech/TensorFlowTTS, pull requests merged in 2020-08, with the labels that each got.

#173 [Android]add queue to synthezie long sentence.
  examples/android/README.md
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/MainActivity.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/Player.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/dispatcher/OnTtsStateListener.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/dispatcher/TtsStateDispatcher.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/AbstractModule.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/FastSpeech2.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/MBMelGan.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/InputWorker.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/TtsManager.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/TtsPlayer.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/utils/NumberNorm.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/utils/Processor.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/utils/ThreadPoolManager.java
  examples/android/app/src/main/res/layout/activity_main.xml
Labels: Feature Request 🤗, TFLite, enhancement 🚀

#175 fix multi-band melgan order
  tensorflow_tts/inference/auto_model.py
Labels: enhancement 🚀

#177 [Android] added speed control
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/MainActivity.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/module/FastSpeech2.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/InputWorker.java
  examples/android/app/src/main/java/com/tensorspeech/tensorflowtts/tts/TtsManager.java
  examples/android/app/src/main/res/layout/activity_main.xml
Labels: Feature Request 🤗, enhancement 🚀

#184 💉 Update README, pretrained link for korean.
  README.md
  examples/fastspeech2/README.md
  examples/multiband_melgan/README.md
  examples/tacotron2/README.md
Labels: documentation 📝

#147 Multi-speaker Fast speech 2 with MFA phoneme and durations
  .gitignore
  examples/fastspeech2_multispeaker/README.md
  examples/fastspeech2_multispeaker/conf/fastspeech2libritts.yaml
  examples/fastspeech2_multispeaker/fastspeech2_dataset.py
  examples/fastspeech2_multispeaker/libri_experiment/prepare_libri.ipynb
  examples/fastspeech2_multispeaker/scripts/build.sh
  examples/fastspeech2_multispeaker/scripts/docker/Dockerfile
  examples/fastspeech2_multispeaker/scripts/interactive.sh
  examples/fastspeech2_multispeaker/scripts/train_libri.sh
  examples/fastspeech2_multispeaker/train_fastspeech2.py
  examples/mfa_extraction/README.md
  examples/mfa_extraction/fix_mismatch.py
  examples/mfa_extraction/requirements.txt
  examples/mfa_extraction/run_mfa.py
  examples/mfa_extraction/scripts/prepare_mfa.sh
  examples/mfa_extraction/txt_grid_parser.py
  preprocess/preprocess_libritts.yaml
  preprocess/preprocess_multispeaker.yaml
  setup.py
  tensorflow_tts/bin/preprocess.py
  tensorflow_tts/configs/__init__.py
  tensorflow_tts/configs/fastspeech.py
  tensorflow_tts/configs/mb_melgan.py
  tensorflow_tts/configs/tacotron2.py
  tensorflow_tts/datasets/audio_dataset.py
  tensorflow_tts/datasets/mel_dataset.py
  tensorflow_tts/inference/auto_config.py
  tensorflow_tts/inference/auto_model.py
  tensorflow_tts/models/__init__.py
  tensorflow_tts/models/fastspeech.py
  tensorflow_tts/models/fastspeech2.py
  tensorflow_tts/models/mb_melgan.py
  tensorflow_tts/models/melgan.py
  tensorflow_tts/processor/experiment/__init__.py
  tensorflow_tts/processor/experiment/base_processor.py
  tensorflow_tts/processor/experiment/example_processor.py
  tensorflow_tts/processor/kss.py
  tensorflow_tts/trainers/__init__.py
  tensorflow_tts/utils/__init__.py
  tensorflow_tts/utils/cleaners.py
  tensorflow_tts/utils/decoder.py
  tensorflow_tts/utils/griffin_lim.py
  tensorflow_tts/utils/group_conv.py
  tensorflow_tts/utils/ko_dictionary.py
  tensorflow_tts/utils/korean.py
  tensorflow_tts/utils/outliers.py
Labels: Feature Request 🤗, enhancement 🚀

#207 🔧 Fix pqmf
  tensorflow_tts/configs/mb_melgan.py
  tensorflow_tts/models/mb_melgan.py
Labels: enhancement 🚀

#191 Add C++ inference example and code
  examples/cppwin/.gitattributes
  examples/cppwin/.gitignore
  examples/cppwin/README.md
  examples/cppwin/TensorflowTTSCppInference.pro
  examples/cppwin/TensorflowTTSCppInference.sln
  examples/cppwin/TensorflowTTSCppInference/EnglishPhoneticProcessor.cpp
  examples/cppwin/TensorflowTTSCppInference/EnglishPhoneticProcessor.h
  examples/cppwin/TensorflowTTSCppInference/FastSpeech2.cpp
  examples/cppwin/TensorflowTTSCppInference/FastSpeech2.h
  examples/cppwin/TensorflowTTSCppInference/MultiBandMelGAN.cpp
  examples/cppwin/TensorflowTTSCppInference/MultiBandMelGAN.h
  examples/cppwin/TensorflowTTSCppInference/TensorflowTTSCppInference.cpp
  examples/cppwin/TensorflowTTSCppInference/TensorflowTTSCppInference.vcxproj
  examples/cppwin/TensorflowTTSCppInference/TensorflowTTSCppInference.vcxproj.filters
  examples/cppwin/TensorflowTTSCppInference/TextTokenizer.cpp
  examples/cppwin/TensorflowTTSCppInference/TextTokenizer.h
  examples/cppwin/TensorflowTTSCppInference/Voice.cpp
  examples/cppwin/TensorflowTTSCppInference/Voice.h
  examples/cppwin/TensorflowTTSCppInference/VoxCommon.cpp
  examples/cppwin/TensorflowTTSCppInference/VoxCommon.hpp
  examples/cppwin/TensorflowTTSCppInference/ext/AudioFile.hpp
  examples/cppwin/TensorflowTTSCppInference/ext/CppFlow/include/Model.h
  examples/cppwin/TensorflowTTSCppInference/ext/CppFlow/include/Tensor.h
  examples/cppwin/TensorflowTTSCppInference/ext/CppFlow/src/Model.cpp
  examples/cppwin/TensorflowTTSCppInference/ext/CppFlow/src/Tensor.cpp
  examples/cppwin/TensorflowTTSCppInference/ext/ZCharScanner.cpp
  examples/cppwin/TensorflowTTSCppInference/ext/ZCharScanner.h
Labels: Feature Request 🤗, enhancement 🚀

#231 Add finetuning (--pretrained) option to training scripts
  examples/fastspeech/README.md
  examples/fastspeech/train_fastspeech.py
  examples/fastspeech2/README.md
  examples/fastspeech2/train_fastspeech2.py
  examples/fastspeech2_libritts/train_fastspeech2.py
  examples/melgan.stft/README.md
  examples/melgan.stft/train_melgan_stft.py
  examples/melgan/README.md
  examples/melgan/train_melgan.py
  examples/multiband_melgan/README.md
  examples/multiband_melgan/train_multiband_melgan.py
  examples/multiband_pwgan/train_multiband_pwgan.py
  examples/tacotron2/README.md
  examples/tacotron2/train_tacotron2.py
Labels: documentation 📝, enhancement 🚀

#232 replace substring *multispeaker* to *libritts* of variables names in …
  examples/fastspeech2_libritts/scripts/build.sh
  examples/fastspeech2_libritts/scripts/train_libri.sh
  examples/fastspeech2_libritts/train_fastspeech2.py
  examples/mfa_extraction/txt_grid_parser.py
Labels: documentation 📝

#233 replace "preprocess_libritts.yaml" to "libritts_preprocess.yaml" in the scripts of fastspeech2_libritts
  examples/fastspeech2_libritts/README.md
  examples/fastspeech2_libritts/scripts/train_libri.sh
  examples/fastspeech2_libritts/train_fastspeech2.py
Labels: documentation 📝
