Repository TensorSpeech/TensorFlowTTS, pull requests merged in 2020-12, with the labels that each got.

#405 Add support for German TTS with Thorsten dataset
  README.md
  preprocess/thorsten_preprocess.yaml
  setup.py
  tensorflow_tts/bin/preprocess.py
  tensorflow_tts/inference/auto_processor.py
  tensorflow_tts/processor/__init__.py
  tensorflow_tts/processor/pretrained/thorsten_mapper.json
  tensorflow_tts/processor/thorsten.py
  tensorflow_tts/utils/cleaners.py
Labels: enhancement 🚀, new feature

#411 🌝 Support FastSpeech resize positional embeddings.
  tensorflow_tts/inference/auto_model.py
  tensorflow_tts/models/fastspeech.py
  test/test_fastspeech.py
  test/test_fastspeech2.py
Labels: enhancement 🚀, new feature

#440 Refactored the Fastspeech TFLite to run on Colab E2E
  notebooks/TensorFlowTTS_FastSpeech_with_TFLite.ipynb
Labels: documentation 📝, enhancement 🚀

#446 ⛱ Add Savable FastSpeech/FastSpeech2/Tacotron2 for TF >= 2.3
  notebooks/fastspeech2_inference.ipynb
  notebooks/fastspeech_inference.ipynb
  notebooks/tacotron2_inference.ipynb
  tensorflow_tts/inference/auto_model.py
  tensorflow_tts/inference/savable_models.py
Labels: enhancement 🚀
