Repository TensorSpeech/TensorFlowTTS, pull requests merged in 2021-08, with the labels that each got.

#640 Synpaflex french dataset tacotron2 and MB-MelGAN support
  README.md
  examples/multiband_melgan/conf/multiband_melgan.synpaflex.v1.yaml
  examples/tacotron2/conf/tacotron2.synpaflex.v1.yaml
  notebooks/prepare_synpaflex.ipynb
  notebooks/tacotron2_inference.ipynb
  preprocess/synpaflex_preprocess.yaml
  tensorflow_tts/bin/preprocess.py
  tensorflow_tts/configs/tacotron2.py
  tensorflow_tts/inference/auto_processor.py
  tensorflow_tts/processor/__init__.py
  tensorflow_tts/processor/pretrained/synpaflex_mapper.json
  tensorflow_tts/processor/synpaflex.py
Labels: enhancement 🚀

#645 🌾 Update README for French model.
  README.md
Labels: documentation 📝

#651 huggingface gradio web demo
  README.md
Labels: enhancement 🚀, Feature Request 🤗
